name: Daily Python Script

on:
  push:
    branches:
      - main  # Adjust the branch as needed
  schedule:
    - cron: '45 12 * * 1-5'  # Run every weekday at 12:45 PM (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      DB_NAME: ${{ env.DB_NAME }}
      COLLECTION_NAME: ${{ env.COLLECTION_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python main.py
